### ISSUE TITLE
ReconMap returns NullPointerException

### ISSUE THREAD

**Issue by MariaHei** [draeger-lab/EscherConverter#35]
When trying to convert the ReconMap SBML file to Escher, there is a NullPointerException.

Options were all set to default: 
![grafik](https://user-images.githubusercontent.com/44357394/56655411-fb5dd600-6692-11e9-8bf0-751f3b06cfb3.png)

Stack trace:
>12:52:16 edu.ucsd.sbrg.escher.gui.SBMLLayoutViewPanel lambda$0 --- WARNUNG: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at javax.swing.SwingWorker.get(Unknown Source)
	at edu.ucsd.sbrg.escher.gui.SBMLLayoutViewPanel.lambda$0(SBMLLayoutViewPanel.java:84)
	at java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at javax.swing.SwingWorker$SwingWorkerPropertyChangeSupport.firePropertyChange(Unknown Source)
	at javax.swing.SwingWorker$SwingWorkerPropertyChangeSupport$1.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at sun.swing.AccumulativeRunnable.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at de.zbit.sbml.layout.y.c.F(YReversibleConsumption.java:50)
	at de.zbit.sbml.layout.y.c.draw(YReversibleConsumption.java:41)
	at de.zbit.sbml.layout.y.R.A(YAbstractSBGNArc.java:69)
	at de.zbit.sbml.layout.y.R.draw(YAbstractSBGNArc.java:43)
	at de.zbit.sbml.layout.y.N.buildConnectingArc(YLayoutBuilder.java:325)
	at de.zbit.sbml.layout.LayoutDirector.handleReactionGlyph(LayoutDirector.java:761)
	at de.zbit.sbml.layout.LayoutDirector.handleReactionGlyphs(LayoutDirector.java:708)
	at de.zbit.sbml.layout.LayoutDirector.buildLayout(LayoutDirector.java:434)
	at de.zbit.sbml.layout.LayoutDirector.run(LayoutDirector.java:863)
	at de.zbit.sbml.layout.y.LayoutDirectionTask.doInBackground(LayoutDirectionTask.java:72)
	at de.zbit.sbml.layout.y.LayoutDirectionTask.doInBackground(LayoutDirectionTask.java:34)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by MariaHei** [comment]
This is probably the same issue as issue #46

**Comment by devkhan** [comment]
Seems like a duplicate of #46, closing.
