### ISSUE TITLE
Setting --gui=false returns JsonParseException

### ISSUE THREAD

**Issue by MariaHei** [draeger-lab/EscherConverter#45]
When using the command line with normal `input` and `output` options and independent of the `--format` option, setting `gui=false` returns the following error:
`com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.FileInputStream@6b2ea799; line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1586)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:521)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:450)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2628)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:854)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:748)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:2926)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2873)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1719)
        at edu.ucsd.sbrg.escher.EscherConverter.parseEscherJson(EscherConverter.java:231)
        at edu.ucsd.sbrg.escher.EscherConverter.parseEscherJson(EscherConverter.java:209)
        at edu.ucsd.sbrg.escher.EscherConverter.convert(EscherConverter.java:196)
        at edu.ucsd.sbrg.escher.EscherConverter.convert(EscherConverter.java:458)
        at edu.ucsd.sbrg.escher.EscherConverter.batchProcess(EscherConverter.java:333)
        at edu.ucsd.sbrg.escher.EscherConverter.commandLineMode(EscherConverter.java:385)
        at de.zbit.Launcher.launchCommandLineMode(Launcher.java:725)
        at de.zbit.Launcher.run(Launcher.java:862)
        at de.zbit.Launcher.<init>(Launcher.java:211)
        at edu.ucsd.sbrg.escher.EscherConverter.<init>(EscherConverter.java:264)
        at edu.ucsd.sbrg.escher.EscherConverter.main(EscherConverter.java:254)`

**Comment by MariaHei** [comment]
I can't currently recreate this error.
