### ISSUE TITLE
Inability to detect nodes leads to NullPointerException

### ISSUE THREAD

**Issue by MariaHei** [draeger-lab/EscherConverter#46]
When trying to convert a sample file from the [Newt project](http://web.newteditor.org/# ) like for example the `Neuronal muscle signalling` from SBGN-ML to SBML, a `NullPointerException` is returned, presumably because a node cannot be found when preprocessing reactions:
```
17.07.2019 11:20:52 edu.ucsd.sbrg.escher.converter.Escher2Standard preProcessReaction --- WARNUNG: Metabolite 'choline' in reaction 'R0' lacks a corresponding node.
17.07.2019 11:20:52 de.zbit.gui.GUITools showErrorMessage --- WARNUNG: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at javax.swing.SwingWorker.get(Unknown Source)
	at edu.ucsd.sbrg.escher.gui.EscherMapDisplay.lambda$0(EscherMapDisplay.java:63)
	at java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at javax.swing.SwingWorker$SwingWorkerPropertyChangeSupport.firePropertyChange(Unknown Source)
	at javax.swing.SwingWorker$SwingWorkerPropertyChangeSupport$1.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at sun.swing.AccumulativeRunnable.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at edu.ucsd.sbrg.escher.converter.Escher2Standard.preProcessReaction(Escher2Standard.java:237)
	at edu.ucsd.sbrg.escher.converter.Escher2Standard.preprocessDataStructure(Escher2Standard.java:217)
	at edu.ucsd.sbrg.escher.converter.Escher2SBML.convert(Escher2SBML.java:100)
	at edu.ucsd.sbrg.escher.EscherConverter.convert(EscherConverter.java:143)
	at edu.ucsd.sbrg.escher.gui.EscherConverterWorker.doInBackground(EscherConverterWorker.java:64)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at javax.swing.SwingWorker.get(Unknown Source)
	at edu.ucsd.sbrg.escher.gui.EscherMapDisplay.lambda$0(EscherMapDisplay.java:63)
	at java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at javax.swing.SwingWorker$SwingWorkerPropertyChangeSupport.firePropertyChange(Unknown Source)
	at javax.swing.SwingWorker$SwingWorkerPropertyChangeSupport$1.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at sun.swing.AccumulativeRunnable.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at edu.ucsd.sbrg.escher.converter.Escher2Standard.preProcessReaction(Escher2Standard.java:237)
	at edu.ucsd.sbrg.escher.converter.Escher2Standard.preprocessDataStructure(Escher2Standard.java:217)
	at edu.ucsd.sbrg.escher.converter.Escher2SBML.convert(Escher2SBML.java:100)
	at edu.ucsd.sbrg.escher.EscherConverter.convert(EscherConverter.java:143)
	at edu.ucsd.sbrg.escher.gui.EscherConverterWorker.doInBackground(EscherConverterWorker.java:64)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by MariaHei** [comment]
This is probably due to mistakes in the files.
