### ISSUE TITLE
NullPointerException when inferring compartment boundaries

### ISSUE THREAD

**Issue by MariaHei** [draeger-lab/EscherConverter#47]
When trying to open `e_coli_core_metabolism.escher.json` with inferring compartment boundaries set to true, a NullPointerException occurs:

![grafik](https://user-images.githubusercontent.com/44357394/61957218-06404380-afbf-11e9-82a4-c02d5b8581c3.png)

```
26.07.2019 16:02:30 de.zbit.gui.GUITools showErrorMessage --- WARNUNG: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at javax.swing.SwingWorker.get(Unknown Source)
	at edu.ucsd.sbrg.escher.gui.EscherMapDisplay.lambda$0(EscherMapDisplay.java:63)
	at java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at javax.swing.SwingWorker$SwingWorkerPropertyChangeSupport.firePropertyChange(Unknown Source)
	at javax.swing.SwingWorker$SwingWorkerPropertyChangeSupport$1.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at sun.swing.AccumulativeRunnable.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at edu.ucsd.sbrg.escher.converter.Escher2SBML.createCompartmentGlyph(Escher2SBML.java:143)
	at edu.ucsd.sbrg.escher.converter.Escher2SBML.convert(Escher2SBML.java:122)
	at edu.ucsd.sbrg.escher.EscherConverter.convert(EscherConverter.java:143)
	at edu.ucsd.sbrg.escher.gui.EscherConverterWorker.doInBackground(EscherConverterWorker.java:64)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by MariaHei** [comment]
The compartment's information read out from the Escher file is indeed null: `c=EscherCompartment [x=null, y=null, width=null, height=null]`

**Comment by draeger** [comment]
That is strange. Can you reproduce when and how this `null`-compartment is being created?

**Comment by MariaHei** [comment]
There is no NullPointerException anymore now, but if all of the compartment's parameters are null, the compartment is simply drawn around the entire canvas. This might be improved.
